<a href="https://colab.research.google.com/github/Yatharth19/ML/blob/main/K_fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold # IT SHUFFLES THE DATA BEFORE SPLITTING INTO K SETS.

In [ ]:
iris=load_iris()

In [ ]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [ ]:
X=iris.data
y=iris.target

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,)

In [ ]:
X.shape

(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [ ]:
folds=StratifiedKFold(n_splits=3) # WILL BE CREATING 3 SETS OF OUR TRAINING DATA
scores_logistic=[]
scores_svm=[]
scores_tree=[]
scores_ranfor=[]


for train_index, test_index in folds.split(X,y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], \
                                       y[train_index], y[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_tree.append(get_score((tree.DecisionTreeClassifier()),X_train,X_test,y_train,y_test))
    scores_ranfor.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [ ]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y,cv=3)

array([0.96, 0.96, 0.94])

In [ ]:
cross_val_score(SVC(gamma='auto'), X, y,cv=3)

array([0.98, 0.98, 0.96])

In [ ]:
cross_val_score(tree.DecisionTreeClassifier(),X,y,cv=3)

array([0.98, 0.92, 1.  ])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),X, y,cv=3)

array([0.98, 0.94, 0.94])

PARAMETER TUNNING USING K FOLD CROSS VALIDATION

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores1)

0.9533333333333334

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=10),X, y, cv=10)
np.average(scores2)

0.96

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=20),X,y, cv=10)
np.average(scores3)

0.96

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=100),X, y, cv=10)
np.average(scores1)

0.9666666666666666